services:
  - type: web
    name: product-price-finder-mcp
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: AUTH_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MY_NUMBER
        sync: false
      - key: DEBUG
        value: false
    healthCheckPath: /mcp/
